name: SQLFluff

on:
  push:
    branches: main

env:
  PYTHON_VERSION: '3.8.12'
  SQLFLUFF_VERSION: '1.4.5'


jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install sqlfluff
        run: "pip install sqlfluff==${{ env.SQLFLUFF_VERSION }}"

      - name: Get changed files in the dbt/models folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: dbt/models.*[.]sql


      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"


#
#
#
#
#      - name: Get changed files
#        id: get_file_changes
#        uses: trilom/file-changes-action@v1.2.4
#        with:
#          output: ' '
#
#      - name: Get changed .sql files in /models to lint
#        id: get_files_to_lint
#        shell: bash -l {0}
#        run: |
#          # Set the command in the $() brackets as an output to use in later steps
#          echo "::set-output name=lintees::$(
#          # Issue where grep regular expressions don't work as expected on the
#          # Github Actions shell, check dbt/models/ folder
#          echo \
#          $(echo ${{ steps.get_file_changes.outputs.files_modified }} |
#          tr -s ' ' '\n' |
#          grep -E '^dbt/models.*[.]sql$' |
#          tr -s '\n' ' ') \
#          $(echo ${{ steps.get_file_changes.outputs.files_added }} |
#          tr -s ' ' '\n' |
#          grep -E '^dbt/models.*[.]sql$' |
#          tr -s '\n' ' ')
#          )"
#      - name: Lint dbt models
#        id: sqlfluff_json
#        if: steps.get_files_to_lint.outputs.lintees != ''
#        shell: bash -l {0}
#        run: sqlfluff lint --dialect bigquery ${{ steps.get_files_to_lint.outputs.lintees }}
##          > annotations.json
##      - name: Annotate
##        uses: yuzutech/annotations-action@v0.3.0
##        with:
##          repo-token: "${{ secrets.GITHUB_TOKEN }}"
##          title: "SQLFluff Lint"
##          input: "./annotations.json"