name: SQLFluff lint

on:
  push:
    branches:
      - main
    paths:
    - 'dbt/**'
    - '.github/workflows/sqlfluff_lint.yml'

env:
  PYTHON_VERSION: '3.8.12'
  SQLFLUFF_VERSION: '1.4.5'


jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install sqlfluff
        run: "pip install sqlfluff==${{ env.SQLFLUFF_VERSION }}"

      - name: Get changed files in the dbt/models folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          separator: " "
          files: |
            **/*.sql

      - name: Run step if any file(s) in the dbt folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "--------> ${{ steps.changed-files-specific.outputs.all_changed_files }}"

      - name: Lint dbt models
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        shell: bash -l {0}
        run: sqlfluff lint --dialect bigquery ${{ steps.changed-files-specific.outputs.all_changed_files }}
