name: SQLFluff lint

on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened' ,'synchronize']
    paths:
      - 'dbt/models/**/*.sql'
#    - ".github/workflows/sqlfluff_lint.yml"


env:
  PYTHON_VERSION: '3.8.12'
  SQLFLUFF_VERSION: '1.4.5'
  CONFIG_URL: ./dbt/.sqlfluff
  PR_NUMBER: ${{ github.event.number }}


jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
#      - name: Install Python ${{ env.PYTHON_VERSION }}
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ env.PYTHON_VERSION }}
#      - name: install sqlfluff
#        run: "pip install sqlfluff==${{ env.SQLFLUFF_VERSION }}"
#
#      - name: Get changed files
#        id: changed-files
#        uses: tj-actions/changed-files@v35.4.4
#        with:
#          files: dbt/models/**/*.sql
#
#      - name: List all changed files
#        run: |
#          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#            echo "$file was changed"
#          done
#
##      - name: Get changed files by PR
##        id: files
##        uses: jitterbit/get-changed-files@v1
##
#      - name:  Lint dbt models
#        shell: bash -l {0}
#        run:
#          sqlfluff lint ${{ steps.changed-files.outputs.all_changed_files }} --config ${{env.CONFIG_URL}};
#
#
#      - name: Get changed files by PR
#        id: changed-files-pr
#        run: gh pr view ${{ env.PR_NUMBER }} --json files -q '.files[].path'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#
#      - name: Get changed files in the dbt/models folder
#        id: changed-files-specific
#        uses: tj-actions/changed-files@v35
#        with:
#          separator: " "
#          files: |
#            **/*.sql
#
#      - name: Run step if any file(s) in the dbt folder change
#        if: steps.changed-files-specific.outputs.any_changed == 'true'
#        run: |
#          echo "One or more files in the docs folder has changed."
#          echo "--------> ${{ steps.changed-files-specific.outputs.all_changed_files }}"
#
#      - name: Lint dbt models
#        if: steps.changed-files-specific.outputs.any_changed == 'true'
#        shell: bash -l {0}
#        run: sqlfluff lint ${{ steps.changed-files-specific.outputs.all_changed_files }} --config ${{ env.CONFIG_URL }}
